### ISSUE TITLE
No ZX0/ZX1/ZX7 to VDP decompressors available

### ISSUE THREAD

**Issue by gameblabla** [mori0091/libmsx#51]
**What's happen? Please describe the problem you met.**
It would be nice to have a way to decompress stuff like ZX0 to the VDP directly without having to decompress to RAM first and then pushing it to the VDP. Doing so would be slower than just do it straight to VDP.

In fact there is no such thing in libmsx for any algo.

**Describe the solution you'd like**
devkitSMS has a ZX7 decompressor available : 
https://github.com/sverx/devkitSMS/blob/86784470529f2c87428b5126e2be25e2e9d91ea6/SMSlib/src/SMSlib_zx7_VRAM.c

msxgl have Bitbuster/Pletter VRAM decompressors
https://github.com/aoineko-fr/MSXgl/blob/main/engine/src/compress/bitbuster.c

However, the algos are quite old and not nearly as good as ZX0/ZX1/ZX7.

Personally i think ZX0/ZX1 are better but ZX7 is also pretty good, especially for screen mode 5 stuff.
Most of my screen mode 5 compresses down to 10kb, which is well under the 16kb that an ASCII16 bank provides and almost fits inside of an ASCII8 bank.

It's also very good for YJK, as the sample image here compresses down to 19.5kb with ZX7 and 18.3kb for ZX0 meaning it can fit inside of two ASCII16 banks. (Other less complex images could potentially fit in a single ASCII16 bank, more complex images would need 3 banks.)
It's less good for screen mode 2 however (ZX0 saves only 512 bytes typically) but it could still play its importance there.

DevkitSMS's own ZX7toVRAM will need some changes for MSX and its own VDP control/data ports and more.
(i tested it as is and it's quite fast for screen mode 2 but it didn't work as is and the graphics were not properly decompressed because it assumes SMS stuff :/)

**Describe alternatives you've considered**
Other algos like Phantasy Star's for SMS are also good considerations.

**Additional context**
Results show that ZX0/ZX1 perform well and have good compression ratios while not being absurdly slow like Exominer. 
Maxim's ZX7 variant is even faster than ZX0/ZX1 and and has ok compression ratios.
![](https://github.com/maxim-zhao/bmp2tilecompressors/blob/master/benchmark.png?raw=true)

**Comment by mori0091** [comment]
ZX0 decompressor is supported. (PR #59)
